### PR TITLE
Update miscopt.html to match ntpd/ntp_loopfilter.c

### PR DESCRIPTION
**Pull request by kuzetsa**
# define CLOCK_ALLAN 11  /\* Allan intercept (log2 s) */

### CODE REVIEW

**Comment by eric-s-raymond** [comment]
Our master repository is at ww.ntpsec.org, and GitHub doesn't seem to provide any way to downkoaad your commits as a patch.  Please email a git-format patch to me at esr@thyrsus.com.

**Comment by dankohn** [comment]
@eric-s-raymond You can add `.patch` to the end of the URL:

https://patch-diff.githubusercontent.com/raw/ntp-project/ntp/pull/14.patch

**Comment by eric-s-raymond** [comment]
Thanks, that tip is useful.

Merged and pushed.

**Comment by kuzetsa** [comment]
github is ... odd.

https://github.com/ntp-project/ntp/pull/14/commits/867f4cfcbbd2b81266fab25cdde39c2877c64b1e

^ this is the only commit which was even part of the original pull request. Github is [_strangely_] convinced that any/all subsequent changes in my forked repo are to be included. (_I'm of the opinion: defaults like that are "pretty silly" [tm]_)

I'm closing the pull request because if I don't, github will just continue to do that even if my current branch contains experimental code which is unrelated to my intended single commit which was shown on the github web gui when I originally created this pull request.

**Pull request closed without merging**
